name: Build

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: |
          npm install -g codecov

      - name: Test the extension
        run: |
          python -m pip install --upgrade -v -e ".[test, examples, docs]"
          python -m pytest

      - name: Linting
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          yarn run lint:check

      - name: Install Pandoc and Sphinx Theme
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install -y pandoc
          python -m pip install pydata-sphinx-theme

      - name: Check docs can be built + links
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: docs
        run: |
          make html
          python -m pytest --check-links
